version: '3'

services:
  app:
    build: ./build
    env_file:
      - ./build/syncdb.env
    volumes: 
      - ./src/:/app
    restart: always
  sftp:
    env_file:
      - ./build/syncdb.env    
    depends_on:
      - app
    image: atmoz/sftp
    volumes:
      - ./src/csql:/app/csql
    ports:
      - "10072:22"
    command: ${SFTPUSER}:${SFTPPASS}:1001
    restart: always